### ISSUE TITLE
Keep background

### ISSUE THREAD

**Issue by merwok** [skreek/skeletor.vim#2]
Hello!  I like to define the background for my terminal emulator (for example a background image 50% opaque), and it works well with many vim themes that don't redefine the background color (e.g. elflord).  In other cases I’ve had to copy and change the them (darkblue) to add ctermbg=NONE.

Can there be an option to get this behaviour?

**Comment by skreek** [comment]
Hey @merwok! I hope i understood your problem, i tried to fix this by adding another variable to the script: ```g:no_bg```. You should be able to deactivate the background by simply adding ```let g:no_bg = 1``` to your ```.vimrc``` file or setting g:no_bg to 1 in vim itself while ur in a session :)

Hope this fixes ur prob! Also sorry for the late response, been kinda busy lately.

Greetings and take care!

**Comment by merwok** [comment]
Hi!  I tried this but I still see the grey background.

I don’t know enough about vim to understand what’s going on :(

**Comment by pdanc** [comment]
@merwok on .vimrc ---> `set termguicolors`
But I prefer 16 colors support. Great job @skreek

**Comment by merwok** [comment]
termguicolors doesn’t change that the background is grey instead of transparent.

**Comment by skreek** [comment]
yo @merwok , maybe we need to share some more information than :)! What OS are you using? and what vim version do u use?

I assume you are using transparent bg in ur terminal than? what terminal is that?
